[Icon Theme]
Name=Memphis98
Comment=Port of Windows 98/2000 icons to KDE Plasma
Inherits=breeze
Example=folder
FollowsColorScheme=true

Directories=actions/16,actions/22,actions/24,actions/32,actions/symbolic,apps/22,apps/48,apps/64,apps/scalable,categories/48,categories/64,categories/scalable,devices/16,devices/48,devices/64,devices/scalable,emblems/24,mimetypes/48,mimetypes/64,mimetypes/scalable,places/48,places/64,places/scalable,status/48,status/64,status/scalable

[actions/16]
Size=16
Context=Actions
Type=Fixed

[actions/22]
Size=22
Context=Actions
Type=Fixed

[actions/24]
Size=24
Context=Actions
Type=Fixed

[actions/32]
Size=32
Context=Actions
Type=Fixed

[actions/symbolic]
Size=48
Context=Actions
Type=Scalable

[apps/22]
Size=22
Context=Applications
Type=Fixed

[apps/48]
Size=48
Context=Applications
Type=Fixed

[apps/64]
Size=64
Context=Applications
Type=Fixed

[apps/scalable]
Size=96
Context=Applications
Type=Scalable

[categories/48]
Size=48
Context=Categories
Type=Fixed

[categories/64]
Size=64
Context=Categories
Type=Fixed

[categories/scalable]
Size=96
Context=Categories
Type=Scalable

[devices/16]
Size=16
Context=Devices
Type=Fixed

[devices/48]
Size=48
Context=Devices
Type=Fixed

[devices/64]
Size=64
Context=Devices
Type=Fixed

[devices/scalable]
Size=96
Context=Devices
Type=Scalable

[emblems/24]
Size=24
Context=Emblems
Type=Fixed

[mimetypes/48]
Size=48
Context=MimeTypes
Type=Fixed

[mimetypes/64]
Size=64
Context=MimeTypes
Type=Fixed

[mimetypes/scalable]
Size=96
Context=MimeTypes
Type=Scalable

[places/48]
Size=48
Context=Places
Type=Fixed

[places/64]
Size=64
Context=Places
Type=Fixed

[places/scalable]
Size=96
Context=Places
Type=Scalable

[status/24]
Size=24
Context=Status
Type=Fixed

[status/48]
Size=48
Context=Status
Type=Fixed

[status/64]
Size=64
Context=Status
Type=Fixed

[status/scalable]
Size=96
Context=Status
Type=Scalable
